name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NOMBRE=Miguel
      - CLI_BET_APELLIDO=Merentiel
      - CLI_BET_DOCUMENTO=4409781
      - CLI_BET_NACIMIENTO=2002-05-10
      - CLI_BET_NUMERO=1000
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NOMBRE=Leandro
      - CLI_BET_APELLIDO=Paredes
      - CLI_BET_DOCUMENTO=4409782
      - CLI_BET_NACIMIENTO=2002-05-10
      - CLI_BET_NUMERO=2000
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NOMBRE=Lautaro
      - CLI_BET_APELLIDO=Blanco
      - CLI_BET_DOCUMENTO=4409783
      - CLI_BET_NACIMIENTO=2002-05-10
      - CLI_BET_NUMERO=3000
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NOMBRE=Ayrton
      - CLI_BET_APELLIDO=Cost
      - CLI_BET_DOCUMENTO=4409784
      - CLI_BET_NACIMIENTO=2002-05-10
      - CLI_BET_NUMERO=4000
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NOMBRE=Martin
      - CLI_BET_APELLIDO=Palermo
      - CLI_BET_DOCUMENTO=4409785
      - CLI_BET_NACIMIENTO=2002-05-10
      - CLI_BET_NUMERO=5000
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
